export const fieldsInit = [
  { id: 0, name: "item_number", checked: true },
  { id: 1, name: "name", checked: true },
  { id: 2, name: "descripction", checked: true },
  { id: 3, name: "price", checked: true },
  { id: 4, name: "qty", checked: true },
  { id: 5, name: "width", checked: true },
  { id: 6, name: "height", checked: true },
  { id: 7, name: "depth", checked: true },
  { id: 8, name: "widthmm", checked: true },
  { id: 9, name: "heightmm", checked: true },
  { id: 10, name: "depthmm", checked: true },
  { id: 11, name: "unit", checked: true },
  { id: 12, name: "notes", checked: true },
];
